@endpoint = http://localhost:5000
@blob_connectionstring = {{$dotenv blob_connectionstring}}

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

HTTP GET https://jannemattila.com

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

TCP jannemattila.com 80

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

NSLOOKUP bing.com

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

IPLOOKUP bing.com

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

NSLOOKUP bing.com 8.8.8.8

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

BLOB POST hello data.csv files {{blob_connectionstring}}

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

BLOB GET data.csv files {{blob_connectionstring}}

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

HTTP POST http://localhost:5000/api/commands
BLOB GET data.csv files {{blob_connectionstring}}
BLOB POST hello data2.csv files {{blob_connectionstring}}

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

INFO HOSTNAME
HTTP POST http://localhost:5000/api/commands
INFO HOSTNAME

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

HTTP POST http://localhost:5000/api/commands
REDIS SET hello mycache account.redis.cache.windows.net:6380,password=key,ssl=True,abortConnect=False
REDIS GET mycache account.redis.cache.windows.net:6380,password=key,ssl=True,abortConnect=False

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

HTTP POST http://localhost:5000/api/commands
SQL QUERY "SELECT TOP (5) * FROM [SalesLT].[Customer]" "Server=tcp:account.database.windows.net,1433;Initial Catalog=db;Persist Security Info=False;User ID=user;Password=password;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

NSLOOKUP account.database.windows.net

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

NSLOOKUP account.privatelink.redis.cache.windows.net 8.8.8.8

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

INFO HOSTNAME

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

INFO ENV

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

INFO ENV COMPUTERNAME

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

HTTP GET https://myip.jannemattila.com

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

NSLOOKUP myip.jannemattila.com

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1

INFO NETWORK
