@endpoint = http://localhost:5000

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1
Content-Type: application/json

{
  "commands": [
    "POST http://localhost:5000/api/commands",
    "GET http://localhost:5000/swagger"
  ]
}
