@endpoint = http://localhost:5000

### Execute commands
POST {{endpoint}}/api/commands HTTP/1.1
Content-Type: application/json

{
  "commands": [
    "HTTP POST http://localhost:5000/api/commands",
    "HTTP GET http://localhost:5000/",
    "HTTP GET http://localhost:5000/swagger",
    "BLOB GET data.csv files DefaultEndpointsProtocol=https;AccountName=demoaccount;AccountKey=key;EndpointSuffix=core.windows.net",
    "BLOB POST hello data2.csv files DefaultEndpointsProtocol=https;AccountName=demoaccount;AccountKey=key;EndpointSuffix=core.windows.net"
  ]
}
