variables:
  repository: 'jannemattila/webapp-network-tester'

trigger:
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - src

name: 1.0.$(Rev:r)
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repository)
        command: build
        arguments:
        Dockerfile: '**/Dockerfile'
        buildContext:
        tags: |
          $(Build.BuildNumber)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repository)
        command: build
        Dockerfile: '**/Full.Dockerfile'
        buildContext:
        tags: |
          $(Build.BuildNumber)-full
          latest-full
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repository)
        command: push
        buildContext:
        tags: |
          $(Build.BuildNumber)
          $(Build.BuildNumber)-full
          latest
          latest-full