name: ci

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "src/**"
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        runtime:
          - os: windows-latest
            rid: win-x64
            singleexe: true
          - os: windows-latest
            rid: win-x64
            singleexe: false
          - os: ubuntu-latest
            rid: linux-x64
            singleexe: true
          - os: macos-latest
            rid: osx-x64
            singleexe: true

    runs-on: ${{ matrix.runtime.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish ${{ matrix.runtime.os }}
        working-directory: src/WebApp
        env:
          BuildSingleExe: ${{ matrix.runtime.singleexe }}
        run: dotnet publish --runtime ${{ matrix.runtime.rid }} --output output

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        if: matrix.runtime.os == 'ubuntu-latest'
        with:
          name: webappnetworktester-linux
          path: |
            src/WebApp/output/webappnetworktester
            src/WebApp/output/webappnetworktester.xml

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        if: matrix.runtime.os == 'macos-latest'
        with:
          name: webappnetworktester-macos
          path: |
            src/WebApp/output/webappnetworktester
            src/WebApp/output/webappnetworktester.xml

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        if: matrix.runtime.os == 'windows-latest' && matrix.runtime.singleexe == true
        with:
          name: webappnetworktester-windows
          path: |
            src/WebApp/output/webappnetworktester.*

      - name: Upload Windows artifacts for IIS
        uses: actions/upload-artifact@v4
        if: matrix.runtime.os == 'windows-latest' && matrix.runtime.singleexe == false
        with:
          name: webappnetworktester-windows-iis
          path: |
            src/WebApp/output/
