name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name"
        required: true
      run_id:
        description: "Run ID of the build"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: webappnetworktester-linux
          path: ./artifacts/linux
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: webappnetworktester-macos
          path: ./artifacts/macos
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: webappnetworktester-windows
          path: ./artifacts/windows
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Windows IIS artifacts
        uses: actions/download-artifact@v4
        with:
          name: webappnetworktester-windows-iis
          path: ./artifacts/windows-iis
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          make_latest: true
          generate_release_notes: true
          files: |
            ./artifacts/linux/webappnetworktester-linux
            ./artifacts/macos/webappnetworktester-macos
            ./artifacts/windows/webappnetworktester-windows
            ./artifacts/windows-iis/webappnetworktester-windows-iis
