name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name"
        required: true
      run_id:
        description: "Run ID of the build"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display structure of downloaded files
        run: ls -R ./artifacts

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: ${{ github.event.inputs.tag_name }}
      #     make_latest: true
      #     generate_release_notes: true
      #     files: |
      #       ./artifacts/linux/webappnetworktester-linux
      #       ./artifacts/macos/webappnetworktester-macos
      #       ./artifacts/windows/webappnetworktester-windows
      #       ./artifacts/windows-iis/webappnetworktester-windows-iis
