name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name"
        required: true
      run_id:
        description: "Run ID of the build"
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display structure of downloaded files
        run: ls -R ./artifacts

      # Compress each artifact to a zip file
      - name: Compress artifacts
        run: |
          for file in $(find ./artifacts -type d); do
            zip -r $file.zip $file
          done

      - name: Display structure of downloaded files
        run: ls -R ./artifacts/*.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          make_latest: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./artifacts/webappnetworktester-linux.zip
            ./artifacts/webappnetworktester-macos.zip
            ./artifacts/webappnetworktester-windows.zip
            ./artifacts/webappnetworktester-windows-iis.zip
